# processes with `nowait` flag start without waiting for signal from flow app
# processes with `nomonitor` flag are not monitored either in terminal or proclogs. Also useful for running short-lived commands (for eg. `uname`)
# processes with no platforms specified would be launched on all platforms by default.

services:
  calibrationd:
    command: calibrationd
    
  plannerd:
    command: plannerd

  controlsd:
    command: controlsd
  
  logmessaged:
    command: logmessaged
    nowait: true
  
  keyvald:
    command: keyvald
    nowait: true
  
  gradled:
    command: ./gradlew desktop:run
    nowait: true
    platforms: ["desktop"]
    
  pandad:
    command: pandad
    nowait: true
    
  ai.flow.app:
    command: "am start --user 0 -n ai.flow.android/ai.flow.android.AndroidLauncher"
    nowait: true
    nomonitor: true
    platforms: ["android"]
   
# NOTE: modeld, camerad, sensord, ui are launched in seperate threads under single process in the java app
# and is monitored in flowinit automatically given necessary permissions (root on android required).
